import pygame

class TextDisplay():
    def __init__(self):
        self.gameFont = pygame.font.Font('src/Heroes Legend.ttf',20)
        self.gameFont2 = pygame.font.Font('src/Heroes Legend.ttf',35)
        self.gameFont3 = pygame.font.Font('src/Heroes Legend.ttf',15)
        
        self.fontTitle = pygame.font.SysFont("comicsansms", 30,italic=True)
        self.fontTitle2 = pygame.font.SysFont("comicsansms", 15,italic=True)
        self.fontTitle3 = pygame.font.SysFont("comicsansms", 18,italic=True)
        self.fontTitleBold = pygame.font.SysFont("comicsansms",20, bold =True)
        self.WHITE = (255,255,255)
        self.BLACK = (0,0,0)
        self.RED = (255,0,0)
        self.GREEN = (0,255,0)
        self.BLUE = (0,0,255)
        self.CYAN = (0,255,255)
        self.MAGENTA = (255,0,255)
        self.YELLOW = (255,255,0)
        self.GREY = (200, 200, 200)
        self. MidnightSlatBlue = (123, 104, 238)
        self.bg_color = pygame.Color('grey12')
        self.BlueViolet = (138,43,226)
        self.Chocolate = (210,105,30)
        self.TURQUOISE = (0,206,209)
        self.NAVY = (0,0,128)
    
    def instructions(self, screen):
        width = screen.get_width()
        centreX = width/2
        textTitle = self.gameFont.render("Instructions and Controls", False, self.RED)
        textTitle2 = self.fontTitle2.render("In Flappy Bird you have to control the bird and make sure you don't",False, self.GREEN)
        textTitle3 = self.fontTitle2.render("crash into the pipes  as you will die. If you go through the pipes succesfully,",False, self.GREEN)
        textTitle4 = self.fontTitle2.render("you will gain one point. To control the bird either click the screen or press",False, self.GREEN)
        textTitle5 = self.fontTitle2.render("the spacebar. If you press either one of these buttons, the bird will fly a",False, self.GREEN)
        textTitle6 = self.fontTitle2.render("certain distance up so make sure you control the bird. If you die press space",False, self.GREEN)
        textTitle7 = self.fontTitle2.render("or click the screen to restart the game. To navigate in the main menu",False, self.GREEN)
        textTitle8 = self.fontTitle2.render("and the bird colour picker screen press the certain buttons with your mouse to", False, self.GREEN)
        textTitle11 = self.fontTitle2.render("to go the certain modes. You can press M at any time to mute the music and U", False, self.GREEN)
        textTitle12 = self.fontTitle2.render("to unmute the music. While your in the game you can press P to pause the game.", False, self.GREEN)
        textTitle13 = self.fontTitle2.render("Made By: Ishan Lakhotia (VSS)", False, self.GREEN)
        textTitle14 = self.fontTitle2.render("If you hit the ground or fly way too high you will also die.", False, self.GREEN)
        textTitle15 = self.fontTitle3.render("Press M to Mute", False, self.RED)
        textTitle16 = self.fontTitle3.render("Press U to Unmute", False, self.WHITE)
        textTitle9 = self.fontTitle3.render("Press Q to Quit", False, self.WHITE)
        textTitle10 = self.fontTitle3.render("Press B For Main Menu", False, self.WHITE) 
        textRect = textTitle.get_rect()
        textRect2 = textTitle2.get_rect()
        textRect3 = textTitle3.get_rect()
        textRect4 = textTitle4.get_rect()
        textRect5 = textTitle5.get_rect()
        textRect6 = textTitle6.get_rect()
        textRect7 = textTitle7.get_rect()
        textRect8 = textTitle8.get_rect()
        textRect11 = textTitle11.get_rect()
        textRect12 = textTitle12.get_rect()
        textRect13 = textTitle13.get_rect()
        textRect14 = textTitle14.get_rect()
        textRect15 = textTitle15.get_rect()
        textRect16 = textTitle16.get_rect()
        textRect9 = textTitle9.get_rect()
        textRect10 = textTitle10.get_rect()
        textRect.center = (centreX, 50)
        textRect2.center = (centreX, 150)
        textRect3.center = (centreX, 200)
        textRect14.center = (centreX, 600)
        textRect4.center = (centreX, 250)
        textRect5.center = (centreX, 300)
        textRect6.center = (centreX, 350)
        textRect7.center = (centreX, 400)
        textRect8.center = (centreX, 450)
        textRect11.center = (centreX, 500)
        textRect12.center = (centreX, 550)
        textRect13.center = (centreX, 640)
        textRect9.center = (475, 665)
        textRect10.center = (100, 665)
        textRect15.center = (460, 100)
        textRect16.center = (100, 100)
        screen.blit(textTitle, textRect)
        screen.blit(textTitle2, textRect2)
        screen.blit(textTitle3, textRect3)
        screen.blit(textTitle4, textRect4)
        screen.blit(textTitle5, textRect5)
        screen.blit(textTitle6, textRect6)
        screen.blit(textTitle7, textRect7)
        screen.blit(textTitle8, textRect8)
        screen.blit(textTitle11, textRect11)
        screen.blit(textTitle12, textRect12)
        screen.blit(textTitle13, textRect13)
        screen.blit(textTitle14, textRect14)
        screen.blit(textTitle15, textRect15)
        screen.blit(textTitle16, textRect16)
        screen.blit(textTitle9, textRect9)
        screen.blit(textTitle10, textRect10)
        
    def birdPicker(self, screen):
        width = screen.get_width()
        centreX = width/2
        textTitle = self.gameFont2.render("Pick Bird Colour", False, self.CYAN)
        textTitle2 = self.fontTitle.render("Blue", False, self.BLUE)
        textTitle3 = self.fontTitle.render("Red", False, self.RED)
        textTitle4 = self.fontTitleBold.render("Press B to go to Main Menu", False, self.WHITE)
        textTitle5 = self.fontTitleBold.render("Press Q to Quit", False, self.WHITE)
        textTitleRect = textTitle.get_rect()
        textTitleRect2 = pygame.Rect(120,300,57,95)
        textTitleRect3 = pygame.Rect(370,300,57,95)
        textTitleRect4 = pygame.Rect(20,625,77,35)
        textTitleRect5 = pygame.Rect(375,625,77,35)
        textTitleRect.center = (centreX, 100)
        #textTitleRect2.center = (150,500)
        #textTitleRect3.center = (400,500)
        screen.blit(textTitle,textTitleRect)
        screen.blit(textTitle2,textTitleRect2)
        screen.blit(textTitle3,textTitleRect3)
        screen.blit(textTitle4, textTitleRect4)
        screen.blit(textTitle5, textTitleRect5)
    def paused(self, screen):
        width = screen.get_width()
        centreX = width/2
        textTitlePause = self.gameFont2.render("Paused", False, self.CYAN)
        textTitle2 = self.gameFont.render("Press C to continue",False, self.GREEN)
        textTitle3 = self.gameFont.render("Press M to Mute", False, self.RED)
        textTitle4 = self.gameFont.render("Press U to Unmute",False, self.WHITE)
        TitleRect = textTitlePause.get_rect()
        TitleRect2 = textTitle2.get_rect()
        TitleRect3 = textTitle3.get_rect()
        TitleRect4 = textTitle4.get_rect()
        TitleRect.center = (centreX, 100)
        TitleRect2.center = (centreX, 300)
        TitleRect3.center = (centreX, 400)
        TitleRect4.center = (centreX, 500)
        screen.blit(textTitlePause, TitleRect)
        screen.blit(textTitle2, TitleRect2)
        screen.blit(textTitle3, TitleRect3)
        screen.blit(textTitle4, TitleRect4)
    